theme: jekyll-theme-cayman
title: Ethical Hacking Roadmap
description: Hands-on journey through labs, tools, and techniques.

show_downloads: false

navigation:
  - title: ğŸ  Home
    url: /
  - title: ğŸ§ª Labs
    url: /labs/
  - title: ğŸ—’ï¸ Notes
    url: /notes/
  - title: ğŸ”— GitHub Repo
    url: https://github.com/5k4rch3r85/ethical-hacking-roadmap

